# Use Node.js 20.14.0-alpine image
FROM node:20.14.0-alpine


# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json first
# COPY package-lock.json .
COPY package.json .

# Install dependencies
RUN npm install

# Copy the rest of your app code
COPY . .


RUN npm run build

ENV PORT=4000

# Expose the port your app runs on
EXPOSE 4000

# Command to run your app
CMD ["npm", "run", "start"]
