import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "@/providers/SessionProvider";
import Footer from "@/components/footer/Footer";
import Header from "@/components/Header/Header";
import { Toaster } from "react-hot-toast";
import ClientProvider from "@/providers/ClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "./public/icon.svg",
  },
};

const nunito = Nunito({
  weight: ["700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito} leading-8 tracking-widest antialiased text-primary-text-color`}
      >
        <NextAuthProvider>
          <ClientProvider>
            <Header />
            <main className="flex-grow flex-row  min-h-screen  pb-[5vh] sm:pb-[8vh]">
              {children}
            </main>
            <Toaster position="bottom-left" reverseOrder={false} />
          </ClientProvider>
        </NextAuthProvider>
        <Footer />
      </body>
    </html>
  );
}
